"""Locators for spring '22"""

K12_lex_locators = {
    "app_launcher": {
        "button": "//div[@class='slds-icon-waffle']",
        "search_bar": "//div/input[@type='search' and @placeholder='Search apps and items...']",
        "search_return_term": "//div//lightning-formatted-rich-text[contains(@class,'al-menu-item')]/span/p/b[text()='{}']",
        "view_all_button": "//button[text()='View All']",
    },

    "placeholder_lookup": {
        "lookup1": "//div[contains(@class,'primaryLabel slds-truncate slds-lookup__result-text') and @title='{}']",
        "lookup2": "//mark[text() = '{}']/ancestor::a",
    },
    "frame": "//iframe[contains(@id, '{}') or contains(@title, '{}') or contains(@name, '{}')]",
    "object_dd": "//h1[contains(@class,'slds-page-header__title')]//a",
    "close_tab": "//div[contains(@class, 'oneGlobalNav')]/descendant::*[@data-key='close']/ancestor::button",
    "input_placeholder": "//input[contains(@placeholder,'{}')]",
    "toast_message": "//span[@class='toastMessage slds-text-heading--small forceActionsText']",
    "validation_error_message": "//li[contains(text(),'{}')]",
    "inline_validation_error_message": "//div[@class='slds-form']/fieldset/div[2][@class='slds-form-element__help' and contains(text(),'{}')]",
    "new_button": "//div[contains(text(),'New')]",
    "save_button": "//button[contains(@class,'slds-button slds-button') and @title='Save']",
    "cancel_button": "//button[contains(@class,'slds-button slds-button') and @title='Cancel']",
    "submit_button": "//button[contains(@class,'slds-button slds-button') and @title='Submit']",
    "assign_reviewers_button": "//div[contains(text(),'Assign Reviewers')]",
    "list_view_menu": "//span[@class='triggerLinkText selectedListView uiOutputText']",
    "list_view_option": "//span[contains(text(),'{}')]",
    "link": "//a[.//span[text()='{}' or contains(text(),'{}')]]",
    "edit_button": "//button[@name='Edit' and contains(@class,'slds-button slds-button_neutral')]",
    "close_button": "//div[contains(@class, 'slds-modal')]/descendant::button[@title='Close this window']",
    "core_pop_up_error_close_button": "//lightning-button-icon[@class = 'slds-float_right slds-popover__close']/button[@title='Close error dialog']",
    "in_app_guidance_prompt": "//div[@class='slds-media__body']/h2[contains(@class,'slds-popover_prompt') and text()='{}']",
    "in_app_guidance_got_it_button": "//button[contains(text(),'{}')]",
    "date_picker_field": "//a[contains(@class,'datePicker')]/span[text()='Date Picker']",
    "date_picker_is_open": "//div[contains(@class,'visible DESKTOP')]",
    "date_picker_value": "//div[contains(@class,'uiDatePickerGrid')]/table[@class='calGrid']//*[text()='Today']",
    "status_dropdown_value": "//lightning-base-combobox-item[@role='option' and @data-value='{}']",
    "modal_header": "//div/h2[text()='{}']",
    "tab": "//a[contains(@class, 'tabHeader slds-context-bar__label-action') and @title='{}']",
    "text": "//*[text()='{}']",
    "new_notification_button": "//span[contains(@class,'counterLabel')]//parent::span[@class='countDot ']",
    "new_notification_bell": "//lightning-icon[contains(@class,'slds-icon-utility-notification')]",    
    "notification_count": "//span[contains(@class,'counterLabel') and text()='{}']",
    "mark_as_read_anchor": "//a[contains(text(),'Mark all as read')]",    

    "application": {
        "header": "//div/descendant::div[contains(@class, 'slds-page-header_record-home')]/descendant::div[text()='{}']",
        "list_view_header": "//div//div/span[text()='Applications']",
        "tabs": "//li[@title='{}']/a[@role='tab']",
        "applicant_response_section_title": "//lightning-accordion[@role='list']//lightning-accordion-section[@role='listitem']/section/div[@class='slds-accordion__summary']/h3//span[@title='{}']",
        "collapse_expand_button": "//button[contains(@class,'section-control')and @aria-expanded='{}']/span[@title='{}']",
        "task_highlighted_field": "//lightning-layout-item[contains(@data-label,'{}')]/slot/c-search-match-indicator/div[contains(@class,'search-match-indicator__field-set')]",
        "ad_hoc_highlighted_field": "//lightning-layout-item[@data-label='{}']/slot/div/c-search-match-indicator/div[contains(@class,'search-match-highlight')]",
        "json_highlighted_field": "//div[@data-testid='json-display-element_child' and @aria-selected='true']/div[contains(@class,'slds-form-element') and contains(text(),'{}')]",
        "child_object_field_is_expanded": "//lightning-primitive-header-factory/span/a//span[contains(@title,'{}')]/ancestor::div//h3/button[@aria-expanded='true']//span[@title='{}']",
        "search_bar": "//lightning-input[@data-testid='application-response-details_search']/div/input[@type='search']",
        "search_clear_button": "//div/button[@data-element-id='searchClear']",
        "application_list_view_selector": "//button[@title='Select a List View']",   
        "application_list_view_name": "//span[contains(@class,'virtualAutocompleteOptionText') and text()='{}']",
        "application_assigned_review": "//a[contains(@href,'{}') and contains(text(), 'View and Manage')]",      
        "application_search": "//input[@type='search' and @name='hed__Application__c-search-input']",     
        "application_refresh_button": "//button[@name='refreshButton']",                     
        "application_list_view": "//span[contains(@class,'slds-var-p-right_x-small uiOutputText') and text()='{}']",
        "application_list_view_record_link": "//a[contains(@class,'slds-truncate outputLookupLink slds-truncate') and @title='{}']",
        "edit_button": "//button[@name='Edit' and contains(@class,'slds-button slds-button_neutral')]",
        'mark_review_status_button': "//button[contains(@class,'slds-button')]/span[contains(@class,'uiOutputText') and text()='{}']",
        "slds_path_option": "//a[contains(@class,'tabHeader')]/span[contains(@class,'title slds-path__title') and text()='{}']",
        "submit_stage_status_button": "//button[contains(@class,'slds-button')]/span[contains(@class,'uiOutputText') and text()='{}']",
        "slds_path_selected": "//a[contains(@class,'tabHeader') and @aria-checked='true']/span[contains(@class,'title slds-path__title') and text()='{}']",
        "checklist_section_name": "//table[@role='grid']/tbody/tr//lightning-primitive-cell-factory[@data-label='Checklist Item']//lightning-primitive-custom-cell//c-event-link-custom-cell/a[@title='{}']/ancestor::c-application-checklist-item-list-view[contains(@data-testid,'{}')]",
        "checklist_refresh_button": "//lightning-button-icon[@data-testid='application-checklist_refresh']/button[@title='Refresh Application Checklist']",
        "checklist_completion_value": "//div[contains(@id,'checklist-progress-bar_label')]/lightning-layout/slot/lightning-layout-item[2]/slot/strong[text()='{}']",
        "checklist_item_column_value": "//table[@role='grid']/thead/tr[./th/lightning-primitive-header-factory/div//span[text()='{}']]/following::lightning-primitive-custom-cell//c-event-link-custom-cell/a[@title='{}']/ancestor::c-application-checklist-item-list-view//lightning-primitive-cell-factory/span/div/lightning-base-formatted-text[text()='{}']",
        "application_mode_selection": "//div[contains(@class,'test-listviewdisplayswitcher')]",   
        "application_mode_selection_item": "//li[@title='Table' and contains(@class,'slds-dropdown__item')]",   
        "display_as_table": "//div[@title='Display as Table' and contains(@class,'slds-dropdown-trigger')]",                       
        "checklist_component": {
            "verify_document_buttons": "//c-desktop-application-material-item-header/div[contains(@class,'application-material-item-name')]//h3[contains(text(),'{}')]/ancestor::c-application-material-item-header/div//lightning-button/button[@title='{}']",
            "task_new_button": "//div[@data-testid='editable-related-list']//div/lightning-button/button[@title='{}']",
            "task_header": "//div//header[@data-testid='editable-related-list-wrapper_record-heading']/h1[text()='{}']",
            "task_modal_footer_buttons": "//div//div/button[@aria-label='{}']",
            "task_save_button": "//div//div[@data-testid='edit-related-list-modal_footer']/button[2][@data-testid='save-button']",
            "task_test_date_picker": "//lightning-datepicker/div/div/input[@name='hed__Test_Date__c']",
            "task_test_form_picklists": "//lightning-input-field/lightning-picklist//button[@name='{}']",
            "add_test_score_button": "//div/div//button[@title='{}']",
            "education_history_checkbox": "//lightning-primitive-cell-checkbox//label/span[text()='Select Item 1']",
            "document_header_status": "//c-application-material-item-header//h3[contains(text(),'{}')]//abbr[@title='{}']",
            "checklist_item_link": "//table[@role='grid']/tbody/tr//lightning-primitive-cell-factory[@data-label='Checklist Item']//lightning-primitive-custom-cell//c-event-link-custom-cell/a[@title='{}']",
            "checklist_progress_bar_title": "//lightning-layout/slot/lightning-layout-item/slot/div[@title='Checklist Progress']",
            "checklist_preview_modal_header_status": "//div[contains(@data-aura-class,'ApplicationMaterialItemViewer')]//div/h3//abbr[@title='{}']",
            "checklist_preview_modal_header": "//div[contains(@class,'ApplicationMaterialItem')]//div//h3[@data-testid='application-material-item-name' and contains(text(),'{}')]",
            "edu_checklist_preview_modal_header_admin": "//div[@data-testid='editable-related-list-wrapper_table-heading']",
            "edu_checklist_preview_modal_header_non_admin": "//div[contains(@class,'application-material-item-name')]",
            "rejection_modal_header": "//div[contains(@class,'modal')]/div/h2[contains(@class,'title') and contains(text(),'Reject')]",
            "rejection_reason_picklist": "//button[@type='button' and @name='Rejection Reason']",
            "rejection_reason_option": "//div[@role='listbox']/lightning-base-combobox-item[@data-value='{}']",
            "rejection_comment": "//div[@data-testid='document-verification-processor_rejection_comments']//textarea[@data-testid='document-rejection-processor_rejectionComment']",
            "rejection_footer_buttons": "//div[contains(@class,'modal-footer')]//slot/lightning-button/button[@title='{}']",
            "task_field_value_numbers": "//div/span[@title='{}']//following-sibling::div/div/lightning-formatted-{}[text()='{}']",
            "task_field_set": "//div[@data-testid='field-set-record-display_record-view-form-container']",
            "task_child_object": "//div[@data-testid='related-list-table']",
            "task_child_object_edu_history": "//div[@data-testid='editable-related-list']",
            "task_json": "//div/div/c-json-display",
            "document_pdf_viewer": "//div[@data-testid='materials-item-viewer_document-viewer']",
            "document_not_submitted": "//div[@data-testid='missing-item-illustration']",
            "task_field_value_text": "//div/span[@title='{}']//following-sibling::div/div/p[contains(text(),'{}')]",
            "task_field_text_area": "//div/span[@title='{}']//following-sibling::div/div//textarea[contains(text(),'{}')]",
            "task_field_contact": "//div/span[@title='{}']//following-sibling::div/div/a[contains(@href,'{}') and @title='{}']",
            "task_field_url": "//div/span[@title='{}']//following-sibling::div//lightning-formatted-url/a[contains(@href,'{}')]",
            "task_field_phone": "//div/span[@title='{}']//following-sibling::div//lightning-formatted-phone/a[@href='tel:{}']",
            "default_document_not_available_message": "//div//div/c-applicant-content-masked-viewer/c-illustration-library/preceding::div/h3[@data-testid='application-material-item-name' and contains(text(),'{}')]",
            "no_access_message_default": "//div/h3[@data-testid='application-material-item-name' and contains(text(),'{}')]//following::c-illustration-library[@data-testid='applicant-material-viewer_noaccess-item']//div/p[contains(text(),'{}')]",
            "no_access_message_custom": "//div/h3[@data-testid='application-material-item-name' and contains(text(),'{}')]//following::div/c-applicant-content-masked-viewer//lightning-formatted-rich-text[@data-testid='applicant-material-viewer_hidden-content-message']/span//h3[contains(text(),'{}')]",
            "instructional_message_custom": "//div/h3[@data-testid='application-material-item-name' and contains(text(),'{}')]//following::div/c-applicant-content-masked-viewer/div/lightning-formatted-rich-text[@data-testid='applicant-material-viewer_instruction-message']/span//p[contains(text(),'{}')]",
            "rejection_banner_message": "//div/h3[@data-testid='application-material-item-name' and contains(text(),'{}')]//following::div[@data-testid='materials-item-viewer_document-rejected-title']//div[@class='slds-media__body']/lightning-layout/slot/lightning-layout-item[@data-testid='documented-rejected-notification-message']/slot[contains(text(),'{}')]",
        },

        "manage_reviewers": {
            "add_manage_reviewers_button": "//flexipage-component2[@data-component-id='flexipage_tabset2']//div//lightning-button[@data-testid='application-review-assignment_{}-reviewers']/button[@title='{}']",
            "add_manage_reviewers_single_button": "//button[@title='{}']",      
            "modal_search": "//div//lightning-layout//slot/lightning-layout-item/slot/c-search[@data-testid='manage-reviewers_search']//following::div/c-single-lookup//div/input[@type='text']",
            "modal_type_menu": "//div/lightning-base-combobox//div/input[@role='combobox']",
            "modal_type_menu_selection": "//lightning-base-combobox-item[@data-value='{}]",
            "modal_add_button": "//div//lightning-layout-item//slot/lightning-button[@data-testid='manage-reviewers_add-reviewer-btn']",
            "modal_user_selection": "//c-single-lookup-option/li[@role='presentation']/div//span[text()='{}']",
            "modal_user_selection_type": "//c-single-lookup-option/li[@role='presentation']/div//span[contains(@class,'slds-media__body')]/span[contains(@class, 'slds-listbox__option-meta_entity')]",
            "modal_type_selection": "//c-search//lightning-combobox//div/lightning-base-combobox//div/button[@type='button']",
            "modal_type_selection_option": "//lightning-base-combobox-item[@data-value='{}']",
            "modal_search_clear_button": "//slot/c-search//div/button[@title='Clear selection']",
            "reviewer_section_name_status": "//lightning-layout[@data-testid='reviews']/slot/lightning-layout-item[@data-testid='application-review_reviewer-type']/slot/p[@data-testid='application-review_reviewer' and text()='{}']//following::lightning-layout-item[@data-testid='application-review_status']/slot[text()='{}']",
            "modal_remove_button": "//lightning-primitive-cell-factory/span/div/lightning-base-formatted-text[text()='{}']//following::lightning-primitive-cell-button/lightning-button-icon/button[@name='Remove']",
            "modal_remove_button_disabled": "//lightning-primitive-cell-factory/span/div/lightning-primitive-cell-button/lightning-button-icon[@style='pointer-events: none;']/button[@name='Remove']",
            "modal_remove_reviewer_button": "//div/lightning-datatable/div[2]/div/div/table/tbody/tr/td[3]/lightning-primitive-cell-factory/span/div/lightning-primitive-cell-button",
            "notification_message": "//div//div//li/a/div//div/span[contains(@class,'notification-text') and contains(text(),'{}')]",
        },

        "bulk_reviewers": {
            "modal_type_menu": "//div/lightning-base-combobox//div/input[@role='combobox']",
            "modal_type_menu_selection": "//lightning-base-combobox-item[@data-value='{}]",
            "bulk_modal_next_button": "//div/button[contains(@class,'slds-button slds-button') and @title='Next']",
            "bulk_modal_cancel_button": "//div/button[contains(@class,'slds-button slds-button') and text()='Cancel']",            
            "bulk_modal_selected_applications": "//h3[contains(@id,'subHeader') and text()='Assignments apply to {} selected Applications']",                          
            "modal_user_selection": "//c-single-lookup-option/li[@role='presentation']/div//span[text()='{}']",
            "modal_type_selection": "//c-search//lightning-combobox//div/lightning-base-combobox//div/input[@role='combobox' and @placeholder='Select an Option']",
            "modal_type_selection_option": "//lightning-base-combobox-item[@data-value='{}']",
            "modal_go_back_button": "//div/div/footer/div/div[2]/button[1]",
            "all_list_view": "//span[text()='All' and contains(@class,'selectedListView')]",     
            "no_access_message": "//p[contains(text(),'Looks like you don')]",             
            "go_back_to_list_button": "//button[text()='Go Back to List']",            
            "skipped_reviewers_table": "//div[@title='skipped_reviewers_table']",
            "skipped_reviewers_name": "//lightning-base-formatted-text[contains(text(),'{}')]",            
            "total_skipped_reviews": "//div[@title='total_skipped_reviews']",
            "next_loading_spinner": "//div[1]/div/div/lightning-spinner"
        },

        "applicant_community": {
            "application_list_view_header": "//div//div[@data-testid='applications-div']/div[text()='My Applications']",
            "application_tile": "//c-applicant-application-list-item//lightning-layout-item/slot/div[2][@data-testid='status-div']/div[text()='{}']/preceding::div[1][@data-testid='program-div' and text()='{}']",
            "start_application_button": "//div/lightning-button[@data-testid='start-application-button']",
            "ominiscript_continue_setup_page": "//div//p//a[text()='creating a guided experience with OmniStudio']",
            "submit_application_button": "//lightning-layout-item/slot//div/lightning-button[@data-testid='application-submit_button']",
            "error_message_prompt": "//div[@data-testid='incomplete-items-modal_message']/div/p[contains(text(),'{}')]",
            "modal_submit_button": "//lightning-button[@data-testid='confirmation-modal_submit-button']",
            "modal_got_it_button": "//div[@data-testid='application-submitted-modal_footer']/button[@data-testid='application-submitted-modal_confirm-button' and @title='Got It']",
            "submitted_date": "//lightning-layout-item/slot/lightning-formatted-text[@data-testid='application-submit_application-date' and text()='Submitted: {}']",
            "application_status": "//lightning-layout-item/slot/lightning-formatted-text[@data-testid='application-submit_status' and text()='Status: {}']",
            "application_submitting_to": "//div/lightning-layout/slot/lightning-layout-item/slot/lightning-formatted-text[@data-testid='application-submit_applying-to' and text()='{}']",
            "mobile_community":{
                "carousel_view_item_button": "//div/c-custom-carousel-content//div[text()='{}']//ancestor::div//div/button[text()='View Item']",
                "action_plan_item_page_header": "//lightning-layout/slot//lightning-layout-item/slot/c-applicant-application-material-item-viewer/div//c-mobile-application-material-item-header/div//h1[contains(text(),'{}')]",
                "action_plan_item_back_button": "//lightning-layout-item/slot/c-applicant-application-material-item-viewer//div/lightning-button/button[@title='Back']",
                "document_status": "//div/div[text()='{}']//ancestor::div/div[@data-testid='application-material-item-value' and text()='{}']",
                "task_save_status": "//div//div[@data-testid='application-material-item-state']/p[contains(text(),'{}')]//ancestor::lightning-layout/slot//c-applicant-application-material-item-viewer//div/h1[contains(text(),'{}')]",
                "task_field": "//c-permission-validator[1]/slot[1]/lightning-layout[1]/slot[1]/lightning-layout-item[1]/slot[1]/c-applicant-application-material-item-viewer[1]/div[1]/div[2]/div[1]/c-application-material-item-viewer[1]//input[@placeholder='{}']",
            },
            "editable_fields": "//c-application-material-item-header[@data-testid='materials-item-viewer_item-header']//div/div/h3[@data-testid='application-material-item-name' and contains(text(),'{}')]//following::lightning-input-field/lightning-input//div/input[@Name='{}']",
        },

        "document_checklist_item": {
            "document_header": "//div//div/h1//div/span[text()='{}']",
        },
    },

    "action_plan": {
        "new_plan_button": "//div/button[@type='button' and @title='New Plan']",
        "action_plan_template_input": "//div[contains(@class,'autocompleteWrapper')]/input[@role='combobox' and @placeholder='Search Action Plan Template Versions...']",
        "next_button": "//div/button[contains(@class,'slds-button') and text()='Next']",
        "header_action_plan": "//article/h2[contains(@class,'inlineTitle') and text()='New Action Plan']",
        "action_plan_link": "//div/a/span[contains(@class,'slds-col--padded')]/span[@class='uiOutputText' and text()='{}']",
        "action_plan_record_header": "//div/h1/div[contains(@class,'entityNameTitle') and text()='Action Plan']",
        "ad_hoc_task_form_title": "//div/h2/span[contains(@class,'slds-p-horizontal') and text()='Task Details']",
        "ad_hoc_dci_new_button": "//div[@data-component-id='runtime_industries_actionplan_itemListCardDCI']//div/button[@title='New']",
        "ad_hoc_tasks_new_button": "//div[@data-component-id='runtime_industries_actionplan_itemListCard']//div/button[@title='New']",
        "ad_hoc_dci_form_title": "//div/h2[contains(@class,'title') and text()='New Document Checklist Item']",
        "ad_hoc_form_text_fields": "//div/input[@name='{}']",
        "ad_hoc_task_form_priority": "//button[@type='button' and @name='Priority']",
        "ad_hoc_form_checkbox": "//div/span/input[@type='checkbox' and @name='IsRequired']",
        "action_plan_name": "//label[contains(@class,'label inputLabel uiLabel-left form-element__label uiLabel')]/following-sibling::input",
        "target_object_combo_box": "//a[@role='button' and @class='select' and text()='--None--']",
        "target_object_application": "//a[@role='menuitemradio' and @title='Application']",   
        "save_button": "//button[@title='Save']",      
        "new_task_button": "//button[@title='New Task']",                
        "task_subject": "//input[@name='Subject']",   
        "task_days": "//input[@name='ActivityDate']",    
        "priority_object_combo_box": "//button[@role='combobox' and @name = 'Priority']", 
        "priority_object_normal": "//lightning-base-combobox-item//span[@title='Normal']",  
        "save_task_button": "//button//span[text()='Save']",  
        "task1selection": "//div[contains(@class,'slds-listbox__option')]//span[@title='task1']",  
        "dual_list_right": "//button[contains(@title,'Move selection to Selected Tasks')]",  
        "required_task_checkbox": "//input[contains(@name,'IsRequired')]/following-sibling::label",  
        "publish_template_button": "//button[contains(@title,'Publish Template')]",  
        "confirm_publish_button": "//span[text()='Publish']",                          
    },

    "edit_application": {
        "header_title": "//h2[contains(@class,'slds-modal__title slds-hyphenate slds-text-heading--medium') and contains(text(), 'Edit')]",
        "application_status_dropdown": "//force-record-picklist/force-form-picklist//lightning-combobox/label[text()='Application Status']",
        "application_status_menu": "//lightning-base-combobox-item[@role='option']/span[2]/span[@title='--None--']",
        "application_status_dropdown_value": "//lightning-base-combobox-item[@role='option' and @data-value='{}']",
    },

    "application_review": {
        "header": "//div/descendant::div[contains(@class, 'slds-page-header_record-home')]/descendant::div[text()='{}']",
        "applications_review_list_view": "//span[contains(@class,'slds-var-p-right_x-small uiOutputText') and text()='Application Reviews']",
        "section_title": "//h3[contains(@class, 'slds-section__title')]/span[text()='Information']",
        "application_field": "//div[contains(@class,'uiInput forceSearchInputLookupDesktop')and //input[contains(@title,'Search Application')]]",
        "comments_text_area_feedback_component": "//div[contains(@class,'slds-form-element')]/textarea[contains(@data-field-api-name,'Comments')]",
        "admissions_recommendation_drop_down": "//button[contains(@class,'slds-combobox')and @name='Admissions Recommendation']",
        "submit_recommendation_button": "//div[contains(@class,'slds-var-p-top_medium')]/button[@data-testid='application-review_submission_button' and text()='Submit My Recommendation']",
        "admissions_recommendation_status": "//c-admissions-recommendation[@data-testid='application-review_recommendation_card']//div[@data-testid='admissions-recommendation_recommendation' and text()='{}']",
        "admissions_recommendation_date": "//c-admissions-recommendation[@data-testid='application-review_recommendation_card']//div/lightning-formatted-date-time[@data-testid='admissions-recommendation_end' and text()='{}']",
        "admissions_recommendation_field_value": "//lightning-output-field[contains(@data-output-field-api-name,'{}')]/div/lightning-formatted-text[contains(text(),'{}')]",
        "checklist_navigator_not_started_status": "//button[@title='{}']/ancestor::span[2]/parent::div//div[@data-testid='application-checklist-item-navigator_ap-{}-indicator']",
        "checklist_navigator_status": "//lightning-icon[@data-testid='application-checklist-item-navigator_ap-{}-indicator']/ancestor::div//span/span/button[@title='{}']",
        "checklist_is_expanded": "//c-application-checklist-item-navigator[@role='treeitem' and @title='{}' and @aria-expanded='true']",
        "checklist_expand_button": "//span[contains(@class,'slds-tree__item-label')]/button[@title='{}']/ancestor::div/lightning-button-icon[@data-testid='application-checklist-item-navigator_chevron']",
        "checklist_item_navigator": "//div[contains(@data-testid,'application-checklist-item')]/button[contains(@data-testid,'application-checklist-item') and @title='{}']",
        "checklist_item_navigator_link": "//c-application-checklist-item-navigator[@title='{}']//c-application-checklist-item-navigator/div//button[@title='{}']",
        "checklist_item_navigator_status": "//div[@data-testid='application-checklist-item-navigator_api-nav-item']/button[@title='{}']/ancestor::div/div/lightning-icon[@data-testid='application-checklist-item-navigator_api-{}-indicator' and @title='{}']",
        "enhanced_feedback": {
            "checkbox": "//span/input[@type='checkbox' and @name='{}']",
            "checkbox_value": "//lightning-output-field[contains(@data-output-field-api-name,'{}')]//label/span[@class='slds-checkbox_faux']",
            "duellist": "//div[contains(@class,'slds-dueling')]/ul[@role='listbox']/li[@role='presentation']/div[@role='option' and @data-value='{}']",
            "duellist_move_button": "//div[contains(@class,'slds-dueling-list')]/lightning-button-icon/button[@title='Move selection to Chosen']",
            "dropdown_menu": "//div/div/button[@type='button' and @name='{}']/following-sibling::div/lightning-icon[contains(@class,'slds-icon-utility')]",
            "dropdown_menu_is_closed": "//div/input[@role='combobox' and @name='{}' and @aria-expanded='false']",
            "dropdown_menu_option": "//lightning-base-combobox-item[@role='option']//span/span[@title='{}']",
        },
        "application_review_owner_link": "//records-hoverable-link/div/a//slot/span[text()='{}']",
        "change_owner_icon_button": "//button[contains(@class,'slds-button slds-button') and @title='Change Owner']",
        "change_owner_modal_button": "//div/force-button-group/lightning-button/button[@name='change owner']",
    },

    "snapshot_component": {
        "verify_completed_reviews": "//span[@data-testid='review-snapshot_reviews-completed-label' and text()='{}']",
        "final_decision_date": "//div[@class='final-decision-decision-date']//lightning-formatted-date-time[contains(text(),'{}')]",
        "snapshot_button_text": "//div[@data-testid='review-snapshot_button']/button[contains(text(),'{}')]",
        "my_review_status": "//div[@class='review-detail-title' and text()='Status']/following-sibling::div[@data-testid='review-snapshot_my-review-status' and text()='{}']",
        "my_review_due_date": "//div[contains(@class,'detail-title') and text()='Due']/parent::div/div[2]/lightning-formatted-date-time[contains(text(),'{}')]",
        "admissions_decision_status": "//c-admissions-recommendation/parent::div[@data-testid='review-snapshot_admissions-recommendation']//div[2][@data-testid='admissions-recommendation_recommendation' and text()='{}']",
        "admissions_decision_end_date": "//c-admissions-recommendation/parent::div[@data-testid='review-snapshot_admissions-recommendation']//lightning-formatted-date-time[@data-testid='admissions-recommendation_end' and text()='{}']",
    },

    "contact_locators": {
        "community_login_error": "//div[contains(@class, 'slds-modal__container')]/div[contains(@class, 'modal-body')]"
                                 "/div[contains(text(), 'Looks like this portal user is not a member of a community or your community is down')]",
        "login_to_community": "//a[@name='LoginToNetworkAsUser']",
        "show_more_actions": "//div[contains(@class, 'actionsContainer')]/descendant::li"
                             "/lightning-button-menu[contains(@class, 'menu-button-item slds-dropdown')]"
                             "/button[@aria-expanded='false']",
    },
}